# Generated by Django 5.0.6 on 2024-05-28 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_liderdeequipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='liderdeequipe',
            name='ano',
            field=models.CharField(max_length=10, null=True, verbose_name='Ano de candidatura'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.bairro', verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='candidato',
            field=models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=10, null=True, verbose_name='Já foi candidato?'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='cargo',
            field=models.CharField(max_length=50, null=True, verbose_name='Se sim, qual cargo?'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='cep',
            field=models.CharField(max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='comunidades',
            field=models.TextField(max_length=1000, null=True, verbose_name='Principais bairros/comunidade de votos'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='horario_reuniap',
            field=models.TimeField(null=True, verbose_name='Horário da próxima reunião'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='local_reuniao',
            field=models.CharField(max_length=100, null=True, verbose_name='Local da próxima reunião'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='logradouro',
            field=models.CharField(max_length=100, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='numero',
            field=models.PositiveIntegerField(null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='observacao',
            field=models.TextField(max_length=1000, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='proxima_reuniao',
            field=models.DateField(null=True, verbose_name='Data da próxima reunião'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='reuniao',
            field=models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=10, null=True, verbose_name='Já fez reunião com seus amigos?'),
        ),
        migrations.AddField(
            model_name='liderdeequipe',
            name='votos',
            field=models.IntegerField(null=True, verbose_name='Quantidade de votos'),
        ),
    ]
