# Generated by Django 5.0.6 on 2024-05-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_liderdeequipe_ano_liderdeequipe_bairro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liderdeequipe',
            old_name='horario_reuniap',
            new_name='horario_reuniao',
        ),
    ]
