# Generated by Django 5.0.6 on 2024-05-28 16:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_liderdeequipe_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=250, verbose_name='Completo')),
                ('apelido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apelido')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=30, unique=True, verbose_name='CPF')),
                ('nome_mae', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Pai')),
                ('ddd', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)], verbose_name='DDD')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=10, verbose_name='É Whatsapp?')),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Email')),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=100, null=True, verbose_name='Logradouro')),
                ('numero', models.PositiveIntegerField(null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('observacao', models.TextField(blank=True, max_length=250, null=True, verbose_name='Observação')),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.bairro', verbose_name='Bairro')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.liderdeequipe', verbose_name='Lider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
