# Generated by Django 5.0.6 on 2024-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_amigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome Completo'),
        ),
    ]
