# Generated by Django 5.0.6 on 2024-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_amigo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liderdeequipe',
            name='ano',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ano de candidatura'),
        ),
        migrations.AlterField(
            model_name='liderdeequipe',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Se sim, qual cargo?'),
        ),
        migrations.AlterField(
            model_name='liderdeequipe',
            name='votos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de votos'),
        ),
    ]
