# Generated by Django 5.0.6 on 2024-05-31 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_liderdeequipe_ano_alter_liderdeequipe_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigo',
            name='lider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.liderdeequipe', verbose_name='Lider'),
        ),
    ]
