# Generated by Django 5.0.6 on 2024-06-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_amigo_local_amigo_secao_amigo_zona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amigo',
            old_name='zona',
            new_name='zona1',
        ),
    ]
