# Generated by Django 5.0.6 on 2024-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_zona_amigo_zona1'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='localnova',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local de Votação'),
        ),
        migrations.AddField(
            model_name='amigo',
            name='secaonova',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Seção'),
        ),
        migrations.AddField(
            model_name='amigo',
            name='zonanova',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zona'),
        ),
    ]
