# Generated by Django 5.0.6 on 2024-06-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_amigo_localnova_amigo_secaonova_amigo_zonanova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liderdeequipe',
            name='horario_reuniao',
            field=models.CharField(max_length=20, null=True, verbose_name='Horário da próxima reunião'),
        ),
        migrations.AlterField(
            model_name='liderdeequipe',
            name='proxima_reuniao',
            field=models.CharField(max_length=20, null=True, verbose_name='Data da próxima reunião'),
        ),
    ]
